async function exportPDF() {
    const { jsPDF } = window.jspdf;
    const doc = new jsPDF({
      orientation: 'portrait',
      unit: 'mm',
      format: 'a4'
    });
  
    // Set font for professional look
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(12);
  
    // Header
    doc.setFontSize(18);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(46, 204, 113); // Green color matching theme
    doc.text('Candidate List', 20, 20);
    
    // Optional: Placeholder for logo (uncomment and add image if available)
    // doc.addImage('path/to/logo.png', 'PNG', 160, 10, 30, 20);
    doc.addImage('../../../Public/assets/img/logo.png', 'PNG', 160, 15, 40, 10);
    // Subheader
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(100, 100, 100);
    doc.text('Generated on: ' + new Date().toLocaleDateString(), 20, 28);
  
    // Table data
    const table = document.querySelector('#datatables');
    const headers = Array.from(table.querySelectorAll('thead th')).slice(0, -1);
    const rows = Array.from(table.querySelectorAll('tbody tr'));
  
    const head = [headers.map(th => th.innerText.trim())];
    const body = rows.map(tr => {
      const cells = Array.from(tr.querySelectorAll('td')).slice(0, -1);
      return cells.map(td => td.innerText.trim());
    });
  
    // Table styling
    doc.autoTable({
      head: head,
      body: body,
      startY: 35,
      theme: 'striped',
      headStyles: {
        fillColor: [46, 204, 113], // Green header
        textColor: [255, 255, 255], // White text
        fontSize: 9,
        fontStyle: 'bold'
      },
      bodyStyles: {
        fontSize: 10,
        textColor: [50, 50, 50]
      },
      alternateRowStyles: {
        fillColor: [240, 240, 240] // Light gray for alternate rows
      },
      margin: { top: 35, left: 20, right: 20, bottom: 20 },
      styles: {
        lineColor: [200, 200, 200],
        lineWidth: 0.1
      }
    });
  
    // Footer
    const pageCount = doc.internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFontSize(8);
      doc.setTextColor(100, 100, 100);
      doc.text(
        `Page ${i} of ${pageCount} | Generated by LogiXpress`,
        doc.internal.pageSize.width / 2,
        doc.internal.pageSize.height - 10,
        { align: 'center' }
      );
    }
  
    // Save the PDF
    doc.save('candidates.pdf');
  }



  async function exportInterviewsPDF() {
    const { jsPDF } = window.jspdf;
    const doc = new jsPDF({
      orientation: 'landscape',
      unit: 'mm',
      format: 'a4'
    });
  
    // Set font for professional look
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(12);
  
    // Header
    doc.setFontSize(18);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(46, 204, 113); // Green color matching theme
    doc.text('Interview List', 20, 20);
    
    // Add logo
    doc.addImage('../../../Public/assets/img/logo.png', 'PNG', 240, 15, 40, 10);
  
    // Subheader
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(100, 100, 100);
    doc.text('Generated on: ' + new Date().toLocaleDateString(), 20, 28);
  
    // Table data
    const table = document.querySelector('#datatables');
    const headers = Array.from(table.querySelectorAll('thead th')).slice(0, -1); // Exclude last column (Actions)
    const rows = Array.from(table.querySelectorAll('tbody tr'));
  
    const head = [headers.map(th => th.innerText.trim().replace('\n', ' '))]; // Clean up header text
    const body = rows.map(tr => {
      const cells = Array.from(tr.querySelectorAll('td')).slice(0, -1); // Exclude last column
      return cells.map(td => {
        // Extract text from badge for Status column (index 1)
        if (td.querySelector('.badge')) {
          return td.querySelector('.badge').innerText.trim();
        }
        return td.innerText.trim();
      });
    });
  
    // Table styling
    doc.autoTable({
      head: head,
      body: body,
      startY: 35,
      theme: 'striped',
      headStyles: {
        fillColor: [46, 204, 113], // Green header
        textColor: [255, 255, 255], // White text
        fontSize: 9,
        fontStyle: 'bold'
      },
      bodyStyles: {
        fontSize: 9,
        textColor: [50, 50, 50]
      },
      alternateRowStyles: {
        fillColor: [240, 240, 240] // Light gray for alternate rows
      },
      margin: { top: 35, left: 20, right: 20, bottom: 20 },
      styles: {
        lineColor: [200, 200, 200],
        lineWidth: 0.1
      }
    });
  
    // Footer
    const pageCount = doc.internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFontSize(8);
      doc.setTextColor(100, 100, 100);
      doc.text(
        `Page ${i} of ${pageCount} | Generated by LogiXpress`,
        doc.internal.pageSize.width / 2,
        doc.internal.pageSize.height - 10,
        { align: 'center' }
      );
    }
  
    // Save the PDF
    doc.save('interviews.pdf');
  }